# Generated by Django 4.0.5 on 2022-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.URLField(),
        ),
    ]
