# Generated by Django 4.0.5 on 2022-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_contactme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='contactme',
            options={'ordering': ['email'], 'verbose_name': 'Contact me', 'verbose_name_plural': 'Contact me'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name_plural': 'Projects'},
        ),
    ]
