# Generated by Django 4.0.5 on 2022-07-09 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_icon_alter_project_social_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
