# Generated by Django 4.1.7 on 2023-02-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategorieUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
            ],
            options={
                "verbose_name": "Use categorie",
                "verbose_name_plural": "Uses categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("current", models.BooleanField(default=False)),
                ("order", models.IntegerField()),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("order", models.IntegerField()),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("post", models.CharField(max_length=255)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("current", models.BooleanField(default=False)),
                ("order", models.IntegerField()),
            ],
            options={
                "verbose_name": "Work",
                "verbose_name_plural": "Works",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Use",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField()),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profil.categorieuse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Use",
                "verbose_name_plural": "Uses",
                "ordering": ["order"],
            },
        ),
    ]
