# Generated by Django 4.1.7 on 2023-02-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profil", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
    ]
